<script lang="ts">
  import { onMount } from "svelte";
  import { createExam, deleteExam, getSemesterDashboard, listClasses, listExams, type ClassRecord, type Exam, type SemesterDashboard } from "$lib/api";
  import { formatDurationShort, formatMinutesShort } from "$lib/format";
  let classes = $state<ClassRecord[]>([]); let semester = $state(""); let dashboard = $state<SemesterDashboard | null>(null); let exams = $state<Exam[]>([]); let title = $state(""); let classId = $state<number | null>(null); let examDate = $state(""); let target = $state<number | undefined>(); let error = $state(""); let busy = $state(false);
  async function refresh() { try { classes = await listClasses(); semester ||= classes[0]?.semester ?? ""; classId ??= classes[0]?.id ?? null; if (semester) dashboard = await getSemesterDashboard(semester); exams = await listExams(); error = ""; } catch (e) { error = String(e); } }
  async function addExam(event: SubmitEvent) { event.preventDefault(); if (!classId || !title.trim() || !examDate || busy) return; busy = true; try { await createExam({ class_id: classId, title: title.trim(), exam_date: examDate, target_study_minutes: target ?? null }); title = ""; target = undefined; exams = await listExams(); } catch (e) { error = String(e); } finally { busy = false; } }
  onMount(() => { void refresh(); });
</script>

<main class="container"><p class="eyebrow">Semester view</p><h1>Semester</h1><p class="page-intro">See the workload you are actually carrying across classes.</p>
  <label class="semester">Semester<select bind:value={semester} onchange={() => void getSemesterDashboard(semester).then(value => dashboard = value)}>{#each [...new Set(classes.map(c => c.semester))] as value}<option value={value}>{value}</option>{/each}</select></label>
  {#if dashboard}<section class="summary"><span><strong>{formatDurationShort(dashboard.tracked_seconds)}</strong>Tracked</span><span><strong>{dashboard.completed_tasks}</strong>Completed tasks</span><span><strong>{dashboard.upcoming_deadlines}</strong>Due in 14 days</span></section><section><h2>By class</h2><div class="classes">{#each dashboard.classes as item}<article><h3>{item.course_code}</h3><strong>{formatDurationShort(item.tracked_seconds)}</strong><p>{item.completed_tasks} completed · {item.open_tasks} open · {item.upcoming_deadlines} due soon</p></article>{:else}<p class="empty">Create classes for this semester first.</p>{/each}</div></section>{/if}
  <section><h2>Exam Mode</h2><p class="muted">Each exam creates a real exam-prep task, so timers and Study Blocks work normally.</p><form class="exam-form" onsubmit={addExam}><input required placeholder="Midterm" bind:value={title} /><select required bind:value={classId}>{#each classes as item}<option value={item.id}>{item.course_code}</option>{/each}</select><input required type="date" bind:value={examDate} /><input type="number" min="0" placeholder="Study target (min)" bind:value={target} /><button disabled={busy}>Add exam</button></form><div class="exams">{#each exams as exam}<article><div><strong>{exam.course_code} · {exam.title}</strong><p>{exam.exam_date} · {formatMinutesShort(exam.tracked_minutes)} tracked{#if exam.target_study_minutes} of {formatMinutesShort(exam.target_study_minutes)} target{/if}</p></div><button class="quiet" onclick={() => void deleteExam(exam.id).then(() => listExams().then(value => exams = value))}>Delete</button></article>{:else}<p class="empty">No exams added.</p>{/each}</div></section>
  {#if error}<p class="error">{error}</p>{/if}
</main>
<style>
  .semester{display:grid;gap:5px;max-width:300px;font-size:12px;color:var(--muted)}section{border-top:1px solid var(--line);margin:2rem 0;padding-top:1rem}.summary{display:flex;gap:30px}.summary span{display:flex;flex-direction:column;gap:3px;color:var(--muted);font-size:11px}.summary strong{font-size:20px;color:var(--text)}.classes{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.classes article,.exams article{border:1px solid var(--line);border-radius:8px;padding:13px;background:var(--surface)}.classes h3{margin:0 0 8px}.classes strong{font-size:22px}.classes p,.exams p,.muted{font-size:11px;color:var(--muted)}.exam-form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:7px;align-items:end}.exams{display:grid;gap:6px;margin-top:14px}.exams article{display:flex;justify-content:space-between;align-items:center}.empty{padding:1rem;text-align:center;color:var(--muted);border:1px dashed var(--line)}.error{color:var(--danger)}@media(max-width:700px){.classes{grid-template-columns:1fr 1fr}.exam-form{grid-template-columns:1fr 1fr}.exam-form input:first-child{grid-column:1/-1}}@media(max-width:450px){.classes{grid-template-columns:1fr}.summary{gap:16px}}
</style>
